services:
  db:
    image: mysql:8.0.31
    volumes:
      - dbase:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: adminAcademico
      MYSQL_DATABASE: academico_db

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
volumes:
  dbase: